options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - |
      echo "===== WORKSPACE FILES ====="
      ls -la
      echo "===== END ====="
# 1️⃣ Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA
    - .

# 2️⃣ Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA

# 3️⃣ Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - my-app
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-secrets=DB_PASSWORD=DB_PASSWORD:latest
    - --service-account=$PROJECT_NUMBER@cloudbuild.gserviceaccount.com

images:
- us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA
