options:
  logging: CLOUD_LOGGING_ONLY

steps:

# Step 1: Use secrets inside build
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Secret during build:"
      echo $$BUILD_SECRET

# Step 2: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/my-image:latest'
    - '.'

# Step 3: Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/my-image:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/build-secret/versions/latest
      env: BUILD_SECRET

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/my-image:latest'

