options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: bash
  script: |
    echo "Project      = $PROJECT_ID"
    echo "Commit SHA   = $COMMIT_SHA"
    echo "Short SHA    = $SHORT_SHA"
    echo "Build ID     = $BUILD_ID"
