options:
  logging: CLOUD_LOGGING_ONLY
  
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:${_ENV}'

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:${_ENV}', 
      '.'
    ]

  # 2️⃣ Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:${_ENV}'
    ]

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:${_ENV}',
      '--region', '${_REGION}',
      '--platform', 'managed'
    ]
