options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node:18
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g firebase-tools
        npx firebase --version
        npx firebase deploy --only hosting --project $PROJECT_ID

