options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-jobs/job:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-jobs/job:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'jobs', 'deploy', 'secret-job',
        '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-jobs/job:latest',
        '--region', 'asia-south1',
        '--set-secrets', 'API_KEY=api-key:latest'
      ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-jobs/job:latest'


