options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: PROJECT_ID
  args: ["echo", "Project = $PROJECT_ID"]

- name: COMMIT_SHA
  args: ["echo", "Commit SHA = $COMMIT_SHA"]

- name: SHORT_SHA
  args: ["echo", "Short SHA = $SHORT_SHA"]

- name: BUILD_ID
  args: ["echo", "Build ID = $BUILD_ID"]

