options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
- name: busybox
  args: ["echo", "Project = $PROJECT_ID"]

- name: busybox
  args: ["echo", "Commit SHA = $COMMIT_SHA"]

- name: busybox
  args: ["echo", "Short SHA = $SHORT_SHA"]

- name: busybox
  args: ["echo", "Build ID = $BUILD_ID"]

